---
# reference: https://cirrus-ci.org/guide/writing-tasks/

container:
  cpu: 1
  memory: "2G"

# Sanity checks
lint_markdown_task:
  name: "Lint Markdown"
  container:
    image: "docker.io/library/node:latest"
  install_script: "npm install -g markdownlint-cli"
  lint_script: "markdownlint **/*.md"

lint_yaml_task:
  name: "Lint YAML"
  container:
    image: "docker.io/library/alpine:latest"
  install_script: "apk add --no-cache yamllint"
  lint_script: "yamllint ."

kubeval_kubernetes_task:
  name: "kubeval Kubernetes Files"
  container:
    image: "docker.io/cytopia/kubeval:latest"
  test_script:
    - "kubectl kustomize kubernetes/home/ | kubeval --ignore-missing-schemas"
    - "kubectl kustomize kubernetes/test/ | kubeval --ignore-missing-schemas"
    - "kubectl kustomize kubernetes/prod/ | kubeval --ignore-missing-schemas"

trivy_kubernetes_task:
  name: "trivy Kubernetes Files"
  container:
    image: "docker.io/aquasec/trivy:0.22.0"
  scan_script: "trivy config
                --severity CRITICAL
                --exit-code 1
                kubernetes/"
...
