---
# kubernetes/base/service.yml

apiVersion: "v1"
kind: "Service"
metadata:
  name: "blog-web-service"
  labels:
    app.kubernetes.io/name: "blog-web-service"
    app.kubernetes.io/component: "web"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/component: "web"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: "http"
...
